[package]
name = "cargo-build-sbpf"
version = "0.1.0"
edition = "2021"
description = "Cargo subcommand for building SBPF programs with upstream nightly Rust"
license = "MIT OR Apache-2.0"
repository = "https://github.com/blueshift-gg/cargo-build-sbpf"
authors = ["Claire Fan <claire@blueshift.gg>"]
rust-version = "1.90"
readme = "README.md"
exclude = ["tests"]
keywords = ["solana", "bpf", "sbpf", "cargo", "build"]
categories = ["development-tools", "command-line-utilities"]

[dependencies]
anyhow = "1.0.103"
cargo-config2 = "0.1"
clap = { version = "4.5", features = ["derive"] }
dialoguer = "0.12"
home = "0.5"
which = "8"
rustc_version = "0.4"
toml_edit = { version = "0.23", features = ["serde"] }
